steps:
  - script: |
      echo "Starting doc site build"
      python3 --version
      pip3.8 --version

      pip3.8 install -U --upgrade mkdocs==1.4.2
      pip3.8 install Pygments==2.14.0
      pip3.8 install pymdown-extensions==9.10
      pip3.8 install mkdocs-minify-plugin==0.6.2


      pip3.8 install mkdocs-markdownextradata-plugin==0.2.5
      pip3.8 install mkdocs-redirects==1.2.0
      pip3.8 install pathlib==1.0.1

      pip3.8 install -U mkdocs-material==9.1.2

      which mkdocs
      pip3.8 install markdown-include==0.8.1
      pip3.8 install markdown==3.2.1
      pip3.8 install mkdocs-redirects==1.2.0
      pip3.8 install mkdocs-exclude==1.0.2
      pip3.8 install mkdocs-glightbox==0.3.4
      pip3.8 install mkdocs-open-in-new-tab==1.0.3
      pip3.8 install mkdocs-include-markdown-plugin==4.0.4

      echo == versions ==

      pip3 --version
      python --version
      mkdocs --version
      pip3 freeze | grep mkdocs-material

      echo ========================

      npm i markdown-spellcheck@1.3.1 -g
      mdspell -V
      npm install -g markdown-link-check@3.10.3

      echo == Build Script Start ==

      cwd=`pwd`

      for parentDir in ${cwd}/*/; do
        for dir in ${parentDir}/*/; do
          if [ -d ${dir} ]; then
            dir=${dir%*/}
            dirName=${dir##*/}
            parendDir=${dir%*/}
            parentDirName=${parentDir##*/}
            if [ ${dirName} != "dist" ]; then
            mkdir -p $(Build.ArtifactStagingDirectory)/dist/${parentDir}/${dirName}
            cd ${dir}

            pwd
            mkdocs build -c

            cd ../../..
            ls ${cwd}/${parentDir}/${dirName}/site/
            mv -f ${cwd}/${parentDir}/${dirName}/site/* $(Build.ArtifactStagingDirectory)/dist/${parentDir}/${dirName}/
            fi
          fi
        done
      done

      echo "=== After building ==="
      ls -l $(Build.ArtifactStagingDirectory)/dist/developer-docs
      ls -l $(Build.ArtifactStagingDirectory)/dist/pe-docs
